name: demo_project
description: A Flutter project for eye stress detection.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  image_picker:
  tflite: ^1.1.2
  permission_handler:
 


flutter:
  assets:
    - assets/model.tflite
    - assets/labels.txt
